<a href="https://colab.research.google.com/github/lee7198/openCV/blob/main/openCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip istall numpy

ERROR: unknown command "istall" - maybe you meant "install"


In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import numpy as np

#list
list1 = [0, 1, 2 ,3 ,4, 5, 6, 'hello']
print(list1)
print(type(list1))

#ndarray
a = np.array([0,1,2,3,4,5])
print(a)
print(type(a))
print(a.dtype)


[0, 1, 2, 3, 4, 5, 6, 'hello']
<class 'list'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 7, 'uintp', 'P', 8, 'long', 'l', 'L', 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'b1', 'int64', 'i8', 'uint64', 'u8', 'float16', 'f2', 'float32', 'f4', 'float64', 'f8', 'float128', 'f16', 'complex64', 'c8', 'complex128', 'c16', 'complex256', 'c32', 'object0', 'bytes0', 'str0', 'void0', 'datetime64', 'M8', 'timedelta64', 'm8', 'Bytes0', 'Datetime64', 'Str0', 'Uint64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_'

In [11]:
a = np.array([0,1,2.,3,4,5])
print(a.dtype)
print(a)
print(type(a))
print(a.dtype)

float64
[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [12]:
a = np.array([0,1,2.,3,4,5,'hello'])
print(a)
print(type(a))
print(a.dtype)

['0' '1' '2.0' '3' '4' '5' 'hello']
<class 'numpy.ndarray'>
<U32


In [13]:
a1 = np.array(['1.234','2.345','3.456','4.567','5','6'])
print(a1, a1.dtype)

['1.234' '2.345' '3.456' '4.567' '5' '6'] <U5


In [14]:
a2 = a1.astype('float32')

In [15]:
print(a2, a2.dtype)

[1.234 2.345 3.456 4.567 5.    6.   ] float32


In [16]:
a3 = a2.astype('int32')

In [17]:
print(a3, a3.dtype)

[1 2 3 4 5 6] int32


In [18]:
a = np.arange(12)

In [19]:
print(a.type(a))

t = a.shape

AttributeError: ignored

In [21]:
a2 = np.arange(2, 10)
print(a2, type(a2))
print(a2.shape)

[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)


In [22]:
a3 = np.arange(0, 16, 2)
print(a3, a3.shape)

[ 0  2  4  6  8 10 12 14] (8,)


In [23]:
m = np.array([[0,2,3],
              [3,4,5]])
print(m)
print(m.shape)

[[0 2 3]
 [3 4 5]]
(2, 3)


In [24]:
print(m.shape[0], m.shape[1])

2 3


In [25]:
m2 = np.array([np.arange(3),
               np.arange(3,6)])
print(m2, m2.shape)  

[[0 1 2]
 [3 4 5]] (2, 3)


In [26]:
d = np.arange(12).reshape(3,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
print(d[0][2])

2


In [28]:
print(d[::2, ::2])

[[ 0  2]
 [ 8 10]]


In [29]:
print(d[:,:-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [30]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [31]:
print(a>2)

[False False  True  True  True  True]


In [32]:
print(a[a>2])

[3 4 5 6]


In [33]:
print(a[(a>2) & (a<6)])

[3 4 5]


In [34]:
print(a[a<a.mean()])

[1 2 3]
